---
galaxy_info:
  author: Your Name
  description: "Enterprise-level role to install and configure Tuned, Netdata, and setup automated tuning with systemd timer."
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - bionic
        - focal
  tags:
    - performance
    - monitoring
    - tuned
    - netdata
    - systemd
    - timer
dependencies: []
