---
- name: Include Tuned installation and configuration tasks
  include_tasks: tuned.yml
  when: "'tuned' in ansible_run_tags"
- name: Include Systemd Timer tasks
  include_tasks: timer.yml
  when: "'timer' in ansible_run_tags"
- name: Include Netdata installation and configuration tasks
  include_tasks: netdata.yml
  when: "'netdata' in ansible_run_tags"
