---
- name: Copy tuned-optimizer service file
  template:
    src: tuned-optimizer.service.j2
    dest: /etc/systemd/system/tuned-optimizer.service
    mode: "0644"
  
- name: Copy tuned-optimizer timer file
  template:
    src: tuned-optimizer.timer.j2
    dest: /etc/systemd/system/tuned-optimizer.timer
    mode: "0644"

- name: Reload systemd daemon
  command: systemctl daemon-reload

- name: Enable and start tuned-optimizer.timer
  systemd:
    name: tuned-optimizer.timer
    enabled: yes
    state: started

- name: Ensure tuned-optimizer service is not running (only triggered by timer)
  systemd:
    name: tuned-optimizer.service
    state: stopped
