---
- name: Copy tuned-optimizer service file
  ansible.builtin.template:
    src: tuned-optimizer.service.j2
    dest: /etc/systemd/system/tuned-optimizer.service
    mode: "0644"  
- name: Copy tuned-optimizer timer file
  ansible.builtin.template:
    src: tuned-optimizer.timer.j2
    dest: /etc/systemd/system/tuned-optimizer.timer
    mode: "0644"
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
- name: Enable and start tuned-optimizer.timer
  ansible.builtin.systemd:
    name: tuned-optimizer.timer
    enabled: true
    state: started
- name: Ensure tuned-optimizer service is not running (only triggered by timer)
  ansible.builtin.systemd:
    name: tuned-optimizer.service
    state: stopped
